Copyright (c) 2016, FlexShopper LLC.
All Rights Reserved

UNAUTHORIZED COPYING OF THIS FILE, REDISTRIBUTION AND USE IN SOURCE
AND BINARY FORMS, WITH OR WITHOUT MODIFICATION, VIA ANY MEDIUM 
IS STRICTLY PROHIBITED PROPRIETARY AND CONFIDENTIAL.

